server:
  port: 8888
spring:
#  datasource:
#    url: jdbc:mysql://xinglinglove.cn:3306/xingling_umc?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: Xk98Ypz9^QoarrO
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: falsef
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: stat,wall
#      use-global-data-source-stat: true
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#      stat-view-servlet:
#        login-username: admin
#        login-password: 123456
#        reset-enable: false
#        url-pattern: /druid/*
#      web-stat-filter:
#        url-pattern: /*
  freemarker:
    suffix: .ftl
    charset: utf-8
    cache: false
    template-loader-path: classpath:/templates/
    enabled: true
    expose-request-attributes: true
    request-context-attribute: true
    content-type: text/html
#多数据愿读写分离配置
datasource:
  master:
    username: root
    password: Xk98Ypz9^QoarrO
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://xinglinglove.cn:3306/xingling_umc?useUnicode=true&characterEncoding=UTF-8
  slaver:
    username: root
    password: Xk98Ypz9^QoarrO
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://xinglinglove.cn:3306/xingling_umc?useUnicode=true&characterEncoding=UTF-8
  read: get,select,count,list,query,check
  write: enable,disable,modify,bind,add,create,update,delete,remove,insert,batchInsert,batchSave,batchUpdate,batchDelete
#mybatis
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.xingling.model
#通用mapper
mapper:
  mappers: com.xingling.base.MyMapper
  not-empty: false
  identity: MYSQL
#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  config: classpath:logback.xml

#swagger配置
swagger:
  description: 用户微服务